### PR TITLE
Add idr0081 stats for the prod82 release

### PR DESCRIPTION
**Pull request by sbesson**

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Empty PR description. Please add a short summary of the PR scope and some testing instructions.

**Comment by dominikl** [comment]
👍 Looks good. Guess you want to wait for merge after release to put the date in, right?

**Comment by sbesson** [comment]
I was waiting for us to decide on the expected release date in the upcoming IDR meeting. Once this is agreed, I will update this PR and prepare the static website.

**Comment by dominikl** [comment]
👍

**Pull request merged**
