### PR TITLE
Webclient idr logo

### PR DESCRIPTION
**Pull request by manics**
This adds the logo used in the IDR webclient from https://github.com/openmicroscopy/openmicroscopy/pull/5763 and crops it to remove the empty space on the right.

This will be needed for https://github.com/openmicroscopy/openmicroscopy/pull/6057 since the logo must be hosted outside OMERO.web

Screen Shot 2019-06-17 at 13 22 35
vs
Screen Shot 2019-06-17 at 13 22 45

### CODE REVIEW

**Comment by sbesson** [comment]
Interestingly, the addition of more IDR logos raises the question of whether we will soon want https://idr.openmicroscopy.org/artwork/ mirroring https://www.openmicroscopy.org/artwork/.

Is it worth making the image name more generic by specifying the PNG dimensions or is the expectation that only the OMERO.web client would expect such a size?

**Comment by manics** [comment]
It's 23 pixels tall which is way too low for anything other than a small logo, and an odd size that doesn't correspond to typical icon sizes or anything else. I can't think of where else you'd want it apart from the webclient.

**Comment by sbesson** [comment]
Looks good and  gave me the occasion to review the content of `img/logos` (#64).

As we already have `img/logos/logo-idr.svg` and `mg/logos/logo-idr-white.svg`, I would propose to update the name to `logo-idr-webclient.png` for consistency and maintenance. The leading`logo-` in the name feels quite redundant with the URL but I do not think it is the responsibility of this PR to clean it.

**Comment by manics** [comment]
Done

**Pull request merged**
