### PR TITLE
Html error fixes

### PR DESCRIPTION
**Pull request by manics**
Fixes a couple of HTML errors:
- Incorrect `</div>`
- itr.js requires the variable `TOOLS` defined in the itr.html page only, so should not be loaded by other pages
- Remove old comment

## Updated 2018-08-07
- Rebased
- Clean up footer (there were multiple files)
- Move scripts to header apart from page-specific scripts

### CODE REVIEW

**Comment by jburel** [comment]
The changes prevent the table of apps to be displayed
Excluding for now

--exclude

**Comment by manics** [comment]
@jburel I think I've fixed it with @rgozim's help.

**Comment by jburel** [comment]
Rebuilding now

**Comment by jburel** [comment]
Looks good now with the changes

**Pull request merged**
