### PR TITLE
Add stats for prod122 release

### PR DESCRIPTION
**Pull request by dominikl**
Size for Tara oceans is weird, went down from 2.5Tb to 50Gb. I guess the stats script doesn't estimate the size correctly for NGFF data? @will-moore @sbesson

### CODE REVIEW

**Comment by dominikl** [comment]
Makes sense. Is there a workaround for now?

**Comment by dominikl** [comment]
Just one plate was removed, I might just update the plate count for now and leave the filesize as it is, even it's not 100% correct.

**Comment by sbesson** [comment]
Feels like there is a need to define what the size shown in the front page represents /cc @francesw. A given study can be associated with different entities:
- all submitted data available for download under https://ftp.ebi.ac.uk/pub/databases/IDR/
- the subset of the the data above imported into OMERO
- for converted studies, the data uploaded to the BioImage Archive

**Review by sbesson — COMMENTED** [review]
Should we try to update this ahead of the `prod123` release ?

**Comment by dominikl** [comment]
Replaced by #200 .

**Pull request closed without merging**
