### PR TITLE
Bundle fontawesome

### PR DESCRIPTION
**Pull request by manics**
During the testing of IDR gallery @dominikl pointed out that some external resources were being loaded. This should bundle font-awesome instead of relying on the externally hosted version. Also removes the old fonts.

Note this doesn't bundle the Google fonts, they'be always always been loaded from the external resource and it's unclear whether it'd be as simple as downloading the fonts: https://developers.google.com/fonts/faq

Also note this doesn't deal with the resources bundled by Gallery, only the static website.

### CODE REVIEW

**Comment by joshmoore** [comment]
Has this been deployed somewhere?

**Comment by manics** [comment]
Part of the merge deployment https://snoopycrimecop.github.io/idr.openmicroscopy.org/

**Comment by will-moore** [comment]
Looks good. Deployed site looks fine and the code changes make sense.

**Comment by sbesson** [comment]
:+1: only think I was pondering when looking at the changes was whether we want to add a version the 3rd party CSS stylesheet to communicate and help with future upgrades (like we do in omero-web). For instance, I noticed that these changes also bumped the stylsheet  version from 5.8.1 to 5.9.0.

**Comment by sbesson** [comment]
Briefly discussed https://github.com/IDR/idr.openmicroscopy.org/pull/65#issuecomment-530313734 who suggested we might review to versioning next time we upgrade the static libraries.

**Pull request merged**
