### PR TITLE
Add stats for new studies to be released in prod106

### PR DESCRIPTION
**Pull request by sbesson**
Includes updates to `idr0124` and `idr0115`

Still waiting for `idr0128`, `idr0129` and `idr0130` before updating `releases.tsv` /cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
Failing checks ?

**Comment by sbesson** [comment]
The Jekyll Docker images seemed to have been bumped to Ruby 3.1 while the `pages` tag is still as Jekyll 3.9.0 - it looks like this causes issue when using CSV data files -
````
/usr/local/lib/ruby/3.1.0/csv.rb:1668:in `read': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/readers/data_reader.rb:62:in `read_data_file'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/readers/data_reader.rb:46:in `block in read_data_to'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/readers/data_reader.rb:38:in `each'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/readers/data_reader.rb:38:in `read_data_to'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/readers/data_reader.rb:20:in `read'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/reader.rb:18:in `read'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:164:in `read'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/site.rb:69:in `process'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/command.rb:28:in `process_site'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/gem/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
jekyll 3.9.0 | Error:  wrong number of arguments (given 2, expected 1)
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/gem/gems/jekyll-3.9.0/exe/jekyll:15:in `<top (required)>'
	from /usr/gem/bin/jekyll:25:in `load'
	from /usr/gem/bin/jekyll:25:in `<main>'
```

This is similar to https://github.com/aarongustafson/jekyll-webmention_io/issues/147

Using `jekyll/builder:latest` seems to fix the issue

**Comment by pwalczysko** [comment]
@sbesson PR against youir branch here opened https://github.com/sbesson/idr.openmicroscopy.org/pull/2

**Comment by pwalczysko** [comment]
in https://github.com/sbesson/idr.openmicroscopy.org/pull/2/commits/53ce2cd9974a741f855e9f44e5c1160c476081da I have also added the idr0135 for @dominikl . I have left out the 115 as the same line is already added here by @sbesson

**Comment by dominikl** [comment]
Thanks Petr. Didn’t realise Seb already did the stats for idr0115. Looks good to me 👍

**Pull request merged**
