### PR TITLE
Add statistics for idr0127

### PR DESCRIPTION
**Pull request by sbesson**
Generated using https://github.com/IDR/idr-utils/pull/49.
The last two commits unify the format of the table to comply with the new proposed number of columns

### CODE REVIEW

**Comment by will-moore** [comment]
OK, so I see the extra `Sample Type` column and it's filled in for `idr0127`.
So it needs filling in for the other studies in a followup PR?

**Comment by will-moore** [comment]
I just tried running https://github.com/IDR/idr-utils/pull/49 on idr-next server.

```
$ python idr-utils/scripts/stats.py --disable-fsusage
...
Created session for public@localhost:4064. Idle timeout: 10 min. Current group: Public
Traceback (most recent call last):
  File "idr-utils/scripts/stats.py", line 466, in <module>
    main()
  File "idr-utils/scripts/stats.py", line 459, in main
    append_totals=(ns.format != 'tsv'))
  File "idr-utils/scripts/stats.py", line 303, in stat_top_level
    for study, containers in sorted(studies(study_list).items()):
  File "idr-utils/scripts/stats.py", line 138, in studies
    for line in f:
  File "/usr/lib64/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/usr/lib64/python3.6/fileinput.py", line 360, in _readline
    self._file = self._openhook(self._filename, self._mode)
  File "/usr/lib64/python3.6/fileinput.py", line 400, in hook_compressed
    return open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'idr0087-paci-nuclearimport/experimentA/idr0087-experimentA-filePaths.tsv'
```

**Comment by sbesson** [comment]
Interesting, indeed, there was a mismatch between the type of file and its name for this study. Pushed https://github.com/IDR/idr0087-paci-nuclearimport/commit/a0f5ccff4d3fb64d2b64a31154c7e16d89a5cc66 and pulled the change on `prod105`

**Comment by will-moore** [comment]
`$ python idr-utils/scripts/stats.py --release prod105 idr0123-mota-mifish`

`idr0123-mota-mifish	experimentA	prod105	2251	9	0			0	208	93662	0.196082560248	196082560248	1673	117.20416033950985	1024 x 1024 x 66 x 7 x 1	cell`

**Comment by will-moore** [comment]
Added idr0123 in https://github.com/will-moore/idr.openmicroscopy.org/commit/f59e67e2389c32ca1bf3fa97d274886d8f04b9da

**Pull request merged**
