### PR TITLE
Add the raw data statistics for all published studies

### PR DESCRIPTION
**Pull request by sbesson**
As discused last Monday at the IDR weekly meeting, with the ongoing migration of the public downloadable data to https://ftp.ebi.ac.uk/pub/databases/IDR/ it is useful for end-users to know the amount of data for each study.

This PR uses the statistic that came out of the transfer command to capture the number of files and the total size in bytes for each top-level study.
The last column attempts to normalize the size in TB but arguably this can be recomputed from the third column so leaving it up to the reviewers to decide whether this is useful.

### CODE REVIEW

**Comment by sbesson** [comment]
Note the current state of this PR omits the data for HPA as I am still transferring the last few folders but I will update it as soon as I have the final figures for the current data.
Excluding HPA, the volume of data available for download is ~40M files for ~260TB of data

**Comment by will-moore** [comment]
This looks similar to the file we're using for stats on the IDR home page:
https://raw.githubusercontent.com/IDR/idr.openmicroscopy.org/master/_data/studies.tsv
I haven't compared the numbers, but we'd expect them to be the same, right? Do we need both?
How will this rawdata.tsv be "viewable" on the website?

**Comment by pwalczysko** [comment]
> > How will this rawdata.tsv be "viewable" on the website?
> 
> At the moment it's not and that's something that should be discussed as we rework the download instructions.

I like the table and the idea. Lets remember the main purpose of this: Give the downloaders (== NOT the OME Team) the overview of what are the approximate sizes of what they are downloading.  
Give the information in such a way that it is available at the place where the download happens, at the time of the download.
I would claim that even having a link on the https://ftp.ebi.ac.uk/pub/databases/IDR/ site where this table would be downloadable as, say, pdf, is far far superior to having nothing. Even an outdated table would do.

**Review by pwalczysko — CHANGES_REQUESTED** [review]
Comment on the possible linkage to the to-be-downloaded data. This can be done in a separate PR or by other means, depending on the team-wide discussion result.

**Comment by sbesson** [comment]
> Give the information in such a way that it is available at the place where the download happens, at the time of the download.

Interesting, a top-level file under https://ftp.ebi.ac.uk/pub/databases/IDR/ would be an easy way to colocate this metadata with the data to be downloaded as mentioned in https://github.com/IDR/idr.openmicroscopy.org/pull/188#issuecomment-1825589649. Also thinking of the process, assuming we make the right decisions, managing this information directly under this hierarchy might be even easier as the metadata can be updated directly once the data is copied..

> I would claim that even having a link on the https://ftp.ebi.ac.uk/pub/databases/IDR/ site where this table would be downloadable as, say, pdf, is far far superior to having nothing. Even an outdated table would do.

That probably gets us down to agreeing the minimal requirements for a first version:

1. format: currently set as is TSV mostly to match the existing tabular files in this repository. Can easily be CSV or even JSON
2. data: study name, number of files and total size (bytes) are the bare minimum columns. Everything else is up for discussion (or future amendments)

**Comment by joshmoore** [comment]
> Interesting, a top-level file under https://ftp.ebi.ac.uk/pub/databases/IDR/ would be an easy way to colocate this metadata with the data to be downloaded as mentioned in https://github.com/IDR/idr.openmicroscopy.org/pull/188#issuecomment-1825589649.

Agreed, though would it be easier/as-effective to just have a README per directory then?

**Comment by pwalczysko** [comment]
> Agreed, though would it be easier/as-effective to just have a README per directory then?

I am happy with that @sbesson

**Comment by sbesson** [comment]
Closing in favor of files directly hosted on the public storage infrastructure:
- a top-level CSV file - see https://ftp.ebi.ac.uk/pub/databases/IDR/studies.csv
- individual readme files under each study folder TBD

**Pull request closed without merging**
