### PR TITLE
Add idr0093, idr0097 and idr0098

### PR DESCRIPTION
**Pull request by dominikl**
See title.

~~I had to skip diskusage for `idr0093`, but strangely it still gave me a value for `Size`, just the number of files is missing. I'll try estimate it via `omero fs usage` on Plate level for a few plates (Edit: Fails with OOM).~~

~~Also `releases.tsv` still needs to be updated.~~

### CODE REVIEW

**Comment by sbesson** [comment]
Numbers look good.

If the disk usage command is skipped, my memory is that the stats calculation code makes a best effort to computing the size of the pixel data from the database i.e. using the pixel dimensions + the pixel type per image. Obviously this calculation ignores a number of factors including sub-resolutions and everything related to the file format esp. file compression.

@dominikl this PR is still in draft mode, are you expecting to push additional changes or should we merge and adjust in follow-ups?

**Comment by dominikl** [comment]
I can't get the number of files for idr0093. If someone else can fill them in (and add them to the respective field in releases.tsv too)...

**Comment by dominikl** [comment]
idr0093 number of files added. Thanks @joshmoore !

**Review by joshmoore — APPROVED** [review]
:+1:

**Comment by sbesson** [comment]
Thanks all. We can always come back to the estimation of the file size for idr0093 post release

**Pull request merged**
