### PR TITLE
Use HTTPS for links where possible

### PR DESCRIPTION
**Pull request by manics**
Excludes `_data/tools.json` as this file is being modified in https://github.com/IDR/idr.openmicroscopy.org/pull/28

### CODE REVIEW

**Comment by jburel** [comment]
in ``_includes/head-idr.html``
``http://www.twitter.com/idrnews`` and ``http://www.twitter.com/idrstatus``
can be updated

**Comment by jburel** [comment]
#32 has been merged

**Comment by manics** [comment]
Rebased and updated. I haven't modified the font-awesome URLs because they're comments in a vendored source file

**Comment by jburel** [comment]
@manics font-awesome understood

**Comment by jburel** [comment]
Looks good Thanks

**Pull request merged**
