### PR TITLE
Add prod73 - hpa_07 and idr0075

### PR DESCRIPTION
**Pull request by dominikl**
Current DB size for releases.tsv is still missing. Don't know how to get that.

### CODE REVIEW

**Comment by manics** [comment]
DB is probably the least painful step 😀
```
$ ssh database

$ sudo du -hsc /var/lib/pgsql/9.6
423G    /var/lib/pgsql/9.6
423G    total
```

**Comment by dominikl** [comment]
👍 Thanks @manics

**Comment by dominikl** [comment]
Btw, the stats for hpa look a bit odd. We should check them properly at some point. For now I just added the addtional images/datasets for run 07.

**Comment by joshmoore** [comment]
Thanks, @dominikl. Probably best if we slot in a review of all the values at some point, but definitely good to have something at least reasonable in ASAP.

**Pull request merged**
