### PR TITLE
ITR: point to new url

### PR DESCRIPTION
**Pull request by jburel**
Update URL

### CODE REVIEW

**Comment by sbesson** [comment]
Now deployed at https://snoopycrimecop.github.io/idr.openmicroscopy.org/itr.html for review

**Comment by sbesson** [comment]
@jburel are we ready to go with this for the upcoming deployment?

**Comment by jburel** [comment]
I will push a commit to use https

**Review by sbesson — APPROVED** [review]
Makes sense to me. Tested the CellProfiler notebook and everything worked as expected. Proposing to include in the upcoming `prod96` deployment and we can always fallback to mybinder if we discover issues.

**Pull request merged**
