### PR TITLE
Update links to curated study repositories

### PR DESCRIPTION
**Pull request by sbesson**
Depends on https://github.com/IDR/idr-metadata/pull/369

This updates the references to the curated metadata repositories in our submission pages to point at the new repositories

### CODE REVIEW

**Comment by joshmoore** [comment]
Changes look good. Is the HTML output run through a link checker? (My dim memory is that we didn't get that working)

**Comment by sbesson** [comment]
I think we investigated this while setting up Travis and for Jekyll websites but in the end we limited it to internal linkcheck only in order to minimize false positives.

https://github.com/IDR/idr.openmicroscopy.org/blob/46a028a1f814618c92cc7a981e7f58432a657e53/build.sh#L8

An option would be to selectively reenable for a the URLs like github.com/IDR. At the moment, this would require setting up `--url-ignore` to blacklist the other external links (a la `linkcheck_ignore` in the Sphinx configuration)

**Comment by sbesson** [comment]
@joshmoore activated `htmlproofer` in Travis CI and used the occasion to fix the few broken links.

**Comment by joshmoore** [comment]
Time seems to only have gone from ~45 to ~60. Worth it.

**Pull request merged**
